### PR TITLE
Created and completed Timer project

### PR DESCRIPTION
**Pull request by mona-yyy**
I learned how to make Timer App

### CODE REVIEW

**Comment by ZahraAlismaeel** [comment]
Hey Mona, 

There is an error in your project, from the sound , I am not able to run it

**Comment by mona-yyy** [comment]
I fixed the sound error

**Review by mona-yyy — COMMENTED** [review]
I fixed the sound error

**Comment by mona-yyy** [comment]
> I fixed the sound error

**Pull request closed without merging**
